# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MAS2004 Semester 2 Notes
author: Rosie Shewell Brockway
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.13.3/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.3/dist/contrib/auto-render.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.13.3/dist/katex.min.css


# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    proof_minimal_theme: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath